### ISSUE TITLE
U_S_VFR_Wall_Planning_Chart.tms/ does not exist

### ISSUE THREAD

**Issue by JanC** [jlmcgraw/aviationCharts#4]
Hi,
first, thanks a lot for your scripts.

I have an issue with the `make_seamless_charts.sh` though and I'm not sure if I'm passing the correct paths. 

I ran the 1st step using `./freshenLocalCharts.sh /home/jan/shared/Charts/` and all the downloads completed successfully. 

I then run the 2nd step 
```bash
./make_seamless_charts.sh /home/jan/shared/Charts/aeronav.faa.gov/content/aeronav/ 12-10-2017
```
where I point it to the folder where I downloaded the charts, it unzips all the dowloaded charts but it ends with the error

```
Unzipping all .zip files under /media/sf_MYPASSPORT/Charts/aeronav.faa.gov/content/aeronav to /media/sf_MYPASSPORT/Charts/aeronav.faa.gov/content/aeronav/1_all_tifs
Archive:  /media/sf_MYPASSPORT/Charts/aeronav.faa.gov/content/aeronav/Caribbean/Caribbean_1_VFR_2.zip
  inflating: /media/sf_MYPASSPORT/Charts/aeronav.faa.gov/content/aeronav/1_all_tifs/Caribbean 1 VFR Chart 2.tif  
Archive:  /media/sf_MYPASSPORT/Charts/aeronav.faa.gov/content/aeronav/Caribbean/Caribbean_2_VFR_1.zip
...
...
...

Finished Normalize and copy
Cleaning /media/sf_MYPASSPORT/Charts/aeronav.faa.gov/content/aeronav/merged_tiled_charts/VFR
VFR: U_S_VFR_Wall_Planning_Chart
overlay tile source: /media/sf_MYPASSPORT/Charts/aeronav.faa.gov/content/aeronav/6_tiles/U_S_VFR_Wall_Planning_Chart.tms/ does not exist
```

Did I miss something obvious?

cheers,
Jan

**Comment by jlmcgraw** [comment]
What parameters did you pass to the program?  You'll need to process the planning charts first before doing the VFR charts too since the planning charts are used as an underlay (eg TAC -> Sectional -> Planning)

**Comment by JanC** [comment]
I ran the script with those paths but without any flags
```bash
./make_seamless_charts.sh /home/jan/shared/Charts/aeronav.faa.gov/content/aeronav/ 12-10-2017
```
`/home/jan/shared/Charts/` is the root I used for `./freshenLocalCharts.sh`

I believe my 1st problem is that I should be using the root instead of the `aeronav.faa.gov/content/aeronav/ ` subfolder:

```
./make_seamless_charts.sh  /home/jan/shared/Charts/ 12-10-2017
```

**Comment by JanC** [comment]
This seems to work :)
```
./make_seamless_charts.sh -s -m /home/jan/shared/Charts/ 12-10-2017
```
sorry for the noise, just trying to make it work ;)
