### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by mjtimblin** [jlmcgraw/aviationCharts#9]
Thank you very much for your work on this project. It is very impressive! I would really like to use the clipping shapes for a similar project, but this project doesn't have a license file included in the repository. I don't want to infringe on your copyright. Would you consider adding a license to the repository? Thanks!

**Comment by jlmcgraw** [comment]
It is intended to be GPLv3, I'll upload a license file

If you do end up using the shapes let me know, I'm always interested to find out how this stuff has been helpful

**Comment by mjtimblin** [comment]
Thanks!

I'm working on creating a similar tool but only with the sectional charts functionality. It's programmed using python and the GDAL CLI tools. I don't plan on using the python GDAL library, but I do plan on using Docker to containerize the project for easy use on other platforms.

Here's the project URL, and please let me know if you believe the attributions are insufficient. https://github.com/mjtimblin/Sectional-Charts-to-Leaflet-Map-Tiles
